In [1]:
# Exercise 1 - create a new numpy array to hold the numbers from 1 to 100

import numpy as np

def make_array():
    # Create a list of the numbers 1 to 10
    num_list = list(range(1, 11))
    
    # Create a new numpy array from that list
    new_array = np.array(num_list)
    
    # Print new_array
    print(new_array)

# Run and test the function against the expected output
make_array()


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Exercise 2 - create list of smallish numbers

import numpy as np

def create_new_array(num_list):
    # Create a new numpy array from num_list with data type int16
    new_array = np.array(num_list, dtype=np.int16)
    
    # Print new_array
    print(new_array)

# Run and test the function against the expected output
create_new_array([31112, 32321, 24567, 456, 324, 789])


[31112 32321 24567   456   324   789]


In [9]:
# Exercise 3 - create a numpy array from a pandas dataframe column

import pandas as pd
import numpy as np

def create_fare_series():
    # Create a dataframe from the dataset in the file at the specified URL
    url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'
    df = pd.read_csv(url)
    
    # Create a new numpy array from the Fare column with data type float64
    fare = df['Fare'].to_numpy(dtype=np.float64)
    
    # Print the fare array
    print(fare)

# Run and test the function against the expected output
create_fare_series()


[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

In [13]:
# Exercise 4 - get some statistics from a numpy array created from a data series

import pandas as pd
import numpy as np

def get_age_stats():
    # Load the data from the specified URL
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)
    
    # Create a numpy array from the Age column
    age_array = df['Age'].to_numpy(dtype=np.int32)
    
    # Calculate the average (mean) age
    average_age = round(np.mean(age_array),2)
    
    # Find the age of the oldest person
    oldest_age = np.max(age_array)
    
    # Find the age of the youngest person
    youngest_age = np.min(age_array)
    
    # Print the results
    print(average_age)
    print(oldest_age)
    print(youngest_age)

# Run the function and test against the expected output
get_age_stats()


29.89
42
22


In [17]:
# Exercise 6 - find the mean and standard deviation of wages

import pandas as pd
import numpy as np

def get_income_stats():
    # Load the data from the specified URL
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)
    
    # Create a numpy array from the Income column
    income_array = df['Income'].to_numpy(dtype=np.float64)
    
    # Calculate the mean income
    mean_income = round(np.mean(income_array),3)
    
    # Calculate the standard deviation of income
    std_income = round(np.std(income_array),3)
    
    # Find the highest income
    highest_income = np.max(income_array)
    
    # Find the lowest income
    lowest_income = np.min(income_array)
    
    # Calculate the lowest income as a percentage of the mean
    lowest_income_percentage = round((lowest_income / mean_income) * 100,2)
    
    # Print the results
    print(mean_income)
    print(std_income)
    print(highest_income)
    print(lowest_income_percentage)

# Run the function and test against the expected output
get_income_stats()


63.389
13.937
81.0
34.71


In [19]:
# Exercise 7 - finding the correlation between two series

import pandas as pd
import numpy as np

def get_correlation():
    # Load the data from the specified URL
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)
    
    # Create a numpy array from the Age column
    age_array = df['Age'].to_numpy(dtype=np.float64)
    
    # Create a numpy array from the Income column
    income_array = df['Income'].to_numpy(dtype=np.float64)
    
    # Get the Pearson's Correlation Coefficient
    coef = np.corrcoef(age_array, income_array)
    
    # Print the correlation coefficient matrix
    print(coef)
    
    # Print the correlation coefficient at position [0][1]
    print(coef[0][1])

# Run the function and test against the expected output
get_correlation()


[[ 1.         -0.14787412]
 [-0.14787412  1.        ]]
-0.14787411576068246


In [21]:
# Exercise 8 - increase whole array by 20

import numpy as np

def increase_by_20():
    # Create a numpy array of 12 numbers
    original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])
    
    # Create a new array adding 20 to each of the items in the first array
    new_array = original_array + 20
    
    # Print the new array
    print(new_array)

# Run the function and test against the expected output
increase_by_20()


[21 22 23 24 25 26 27 28 21 22 23 24]


In [23]:
# Exercise 9 - convert Titanic fares into 21st century values

import pandas as pd
import numpy as np

def get_current_fares():
    # Create a dataframe from the Titanic dataset
    url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'
    df = pd.read_csv(url)
    
    # Create a numpy array from the Fare column
    fare_array = df['Fare'].to_numpy(dtype=np.float64)
    
    # Convert the fares into current value by multiplying by the factor
    conversion_factor = 120.7045
    current_fare_array = fare_array * conversion_factor
    
    # Calculate the average fare
    average_fare = np.mean(current_fare_array)
    
    # Find the maximum fare
    max_fare = np.max(current_fare_array)
    
    # Find the minimum fare
    min_fare = np.min(current_fare_array)
    
    # Print the results
    print(average_fare)
    print(max_fare)
    print(min_fare)

# Run the function and test against the expected output
get_current_fares()


3887.1928207428173
61840.4399214
0.0


In [25]:
# Exercise 10 - create a new column in the dataframe from a numpy array

import pandas as pd
import numpy as np

def calculate_inflated_salaries():
    # Load the data from the specified URL
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)
    
    # Create a numpy array from the Income column
    income_array = df['Income'].to_numpy(dtype=np.float64)
    
    # Calculate the inflated salaries with an inflation rate of 3.5%
    inflation_rate = 0.035
    inflated_salaries_array = income_array * (1 + inflation_rate)
    
    # Calculate the Pearson Correlation Coefficient
    coef = np.corrcoef(income_array, inflated_salaries_array)
    
    # Add the new column with inflated salaries to the dataframe
    df['Inflated Income'] = inflated_salaries_array.tolist()
    
    # Display the new dataframe
    print(df)
    
    # Print the correlation coefficient
    print(coef)
    print(coef[0][1])

# Run the function and test against the expected output
calculate_inflated_salaries()


   State  County  Population  Age  Income  Inflated Income
0     TX       1          72   34      65           67.275
1     TX       2          33   42      45           46.575
2     TX       5          25   23      46           47.610
3     TX       6          54   36      65           67.275
4     TX       7          11   42      53           54.855
5     TX       8          28   25      62           64.170
6     TX       9          82   35      66           68.310
7     TX      10           5   40      75           77.625
8     MD      11          61   27      22           22.770
9     MD       2           5   23      69           71.415
10    MD       4          98   25      73           75.555
11    MD       3          64   29      75           77.625
12    MD       2          36   24      65           67.275
13    MD       1          24   25      66           68.310
14    MD       5          34   31      78           80.730
15    MD       6          89   22      81           83.8