In [11]:
# create a new numpy array to hold the numbers from 1 to 100

import numpy as np

def make_array():
    numbers_list = list(range(1, 11))
    new_array = np.array(numbers_list, np.int8)  # Setting the data type to int64
    print(new_array)

make_array()



[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# create list of smallish numbers

import numpy as np

def create_array(num_list):
    new_array = np.array(num_list, np.int16)  # Creating a NumPy array with int16 data type
    print(new_array)

create_array([31112, 32321, 24567, 456, 324, 789])


[31112 32321 24567   456   324   789]


In [13]:
# create a numpy array from a pandas dataframe column

import pandas as pd
import numpy as np

def create_fare_array():
    # Reading the dataset into a DataFrame
    url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'
    df = pd.read_csv(url)

    # Creating a numpy array from the 'Fare' column
    fare = df['Fare'].to_numpy(dtype=np.float64)  # Converting to numpy array with float64 data type
    print(fare)

create_fare_array()


[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

In [14]:
# get some statistics from a numpy array created from a data series

import pandas as pd
import numpy as np

def get_age_stats():
    # Read the dataset into a DataFrame
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)

    # Creating a numpy array from the 'Age' column
    age_array = df['Age'].to_numpy(dtype=np.float64)  

   
    print(np.mean(age_array))  
    print(np.max(age_array))   
    print(np.min(age_array))   


get_age_stats()


29.88888888888889
42.0
22.0


In [15]:
# find the mean and standard deviation of wages

import pandas as pd
import numpy as np

def get_income_stats():
    # Read the dataset into a DataFrame
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)

    # Creating a numpy array from the 'Income' column
    income_array = df['Income'].to_numpy(dtype=np.float64)  

    # Calculate statistics
    mean_income = np.mean(income_array)  # Mean income
    std_dev_income = np.std(income_array)  # Standard deviation of income
    max_income = np.max(income_array)  # Highest income
    min_income_percentage = (np.min(income_array) / mean_income) * 100  # Lowest income as a percentage of the mean

    print(mean_income)
    print(std_dev_income)
    print(max_income)
    print(min_income_percentage)

get_income_stats()


63.388888888888886
13.936916958961463
81.0
34.70639789658195


In [18]:
# finding the correlation between two series

import pandas as pd
import numpy as np

def get_correlation():
    # Read the Income data into a pandas DataFrame
    url = 'https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true'
    df = pd.read_excel(url)

    # Create numpy arrays for 'Age' and 'Income'
    age_array = df['Age'].to_numpy(dtype=np.float64)  # Convert 'Age' to numpy array with float64 data type
    income_array = df['Income'].to_numpy(dtype=np.float64)  # Convert 'Income' to numpy array with float64 data type

    # Calculate Pearson's Correlation Coefficient
    coef = np.corrcoef(age_array, income_array)

    # Print additional information and the correlation coefficient
    print("The matrix gives 4 values showing the correlation between:\n")
    print("|    (Age/Age)        (Age/Income)     |")
    print("|    (Income/Age)     (Income/Income)  |\n")
    print("This suggests that income decreases with age (the correlation is negative so as one increases the other decreases) but that the correlation is quite weak (an absolute correlation would be 1 and no correlation would be 0)\n")
    print(coef)
    print(f"\n{coef[0][1]}")  # Print the correlation coefficient between 'Age' and 'Income'

get_correlation()


The matrix gives 4 values showing the correlation between:

|    (Age/Age)        (Age/Income)     |
|    (Income/Age)     (Income/Income)  |

This suggests that income decreases with age (the correlation is negative so as one increases the other decreases) but that the correlation is quite weak (an absolute correlation would be 1 and no correlation would be 0)

[[ 1.         -0.14787412]
 [-0.14787412  1.        ]]

-0.14787411576068246


In [19]:
# Broadcasting an operation across an array

# Creating a new array to store the result after the operation:
import numpy as np

scores = np.array([29, 25, 15, 22, 30])
percentages = scores / 30 * 100
print(percentages)

#Storing the result in the original array:

import numpy as np

scores = np.array([29, 25, 15, 22, 30])
percentages = scores / 30 * 100
print(percentages)


[ 96.66666667  83.33333333  50.          73.33333333 100.        ]
[ 96.66666667  83.33333333  50.          73.33333333 100.        ]


In [22]:
# increase whole array by 20

import numpy as np

def increase_array():
    # Create a numpy array of 12 numbers
    original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])
    
    # Create a new array by adding 20 to each item in the original array
    new_array = original_array + 20
    
    print(new_array)
increase_array()



[21 22 23 24 25 26 27 28 21 22 23 24]


In [23]:
# convert Titanic fares into 21st century values

import pandas as pd
import numpy as np

def get_current_fares():
    # Read the data into a DataFrame
    titanic_data = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')

    # Create a numpy array from the Fare column
    fares_array = titanic_data['Fare'].to_numpy()

    # Convert fares into current value using the factor 120.7045
    current_fares = fares_array * 120.7045

    # Print the average, maximum, and minimum fares
    print(np.mean(current_fares))
    print(np.max(current_fares))
    print(np.min(current_fares))

get_current_fares()



3887.1928207428173
61840.4399214
0.0


In [26]:
# create a new column in the dataframe from a numpy array
# for work need exel file on github with column "Salary"!!!
import pandas as pd
import numpy as np

def calculate_inflated_salaries():
    # Read the Income data into a pandas DataFrame
    income_data = pd.read_excel('https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true')

    # Create a numpy array from the Salary column
    salaries = income_data['Income'].to_numpy()

    # Calculate expected salaries after an inflation rate of 3.5%
    inflated_salaries = salaries * 1.035

    # Add the inflated salaries as a new column in the DataFrame
    income_data['Inflated_Salary'] = inflated_salaries.tolist()

    # Calculate the Pearson Correlation Coefficient between Salary and Inflated Salary columns
    correlation = np.corrcoef(salaries, inflated_salaries)

    # Display the new DataFrame and print the correlation coefficient
    print(income_data)
    print("Pearson Correlation Coefficient:", correlation[0][1])


calculate_inflated_salaries()


   State  County  Population  Age  Income  Inflated_Salary
0     TX       1          72   34      65           67.275
1     TX       2          33   42      45           46.575
2     TX       5          25   23      46           47.610
3     TX       6          54   36      65           67.275
4     TX       7          11   42      53           54.855
5     TX       8          28   25      62           64.170
6     TX       9          82   35      66           68.310
7     TX      10           5   40      75           77.625
8     MD      11          61   27      22           22.770
9     MD       2           5   23      69           71.415
10    MD       4          98   25      73           75.555
11    MD       3          64   29      75           77.625
12    MD       2          36   24      65           67.275
13    MD       1          24   25      66           68.310
14    MD       5          34   31      78           80.730
15    MD       6          89   22      81           83.8